@extends('frontend.layouts.app')


@section('og')
<title>{{ (!empty($seoData->title) && !empty($seoData)) ? $seoData->title : (settings('site')->meta_title ?? config('app.name')) }}</title>
<meta name="title" content="{{ ( !empty($seoData) && !empty($seoData->meta_title)) ? $seoData->meta_title : settings('site')->meta_title ?? ''}}">
<meta name="description" content="{{ ( !empty($seoData) && !empty($seoData->meta_des)) ? $seoData->meta_des :(settings('site')->meta_description ?? '')}}">
<meta name="keywords" content="{{ ( !empty($seoData) && !empty($seoData->meta_keyword)) ? $seoData->meta_keyword : (settings('site')->meta_keywords ?? '') }}">
<meta name="author" content="Osint">
<meta name="robots" content="index follow" />
<link rel="canonical" href="{{url()->current()}}"/>
<meta property="og:type" content="website" />
<meta property="og:title" content="{{ ( !empty($seoData) && !empty($seoData->meta_title)) ? $seoData->meta_title : settings('site')->meta_title ?? ''}}" />
<meta property="og:description" content="{{ (!empty($seoData) && !empty($seoData->meta_des) ) ? $seoData->meta_des :(settings('site')->meta_description ?? '')}}" />
<meta property="og:url" content="{{url()->current()}}"/>
<meta property="og:image" content="{{ !empty($seoData) ?  getNormalImage('featured_image',$seoData->featured_image) : asset('assets/frontend/images/spyderlab_featured_image.png')}}" />
<meta property="og:image:width" content="850">
<meta property="og:image:height" content="560">
<meta property="og:site_name" content="spyderlab" />
<meta property="og:locale" content="en" />
<meta property="twitter:url" content="{{url()->current()}}">
<meta property="twitter:image" content="{{ !empty($seoData) ? getNormalImage('featured_image',$seoData->featured_image) : asset('assets/frontend/images/spyderlab_featured_image.png')}}">
<meta property="twitter:title" content="{{ ( !empty($seoData) && !empty($seoData->meta_title)) ? $seoData->meta_title : settings('site')->meta_title ?? ''}}">
<meta property="twitter:description" content="{{ ( !empty($seoData) && !empty($seoData->meta_des)) ? $seoData->meta_des :(settings('site')->meta_description ?? '')}}">
<meta name="twitter:description" content="{{ ( !empty($seoData) && !empty($seoData->meta_des)) ? $seoData->meta_des :(settings('site')->meta_description ?? '')}}">
<meta name="twitter:image" content="{{ !empty($seoData) ? getNormalImage('featured_image',$seoData->featured_image) : asset('assets/frontend/images/spyderlab_featured_image.png')}}">
<meta name="twitter:card" value="summary_large_image">
<meta name="twitter:site" value="@spyderlab">
@endsection

@section('content')
<main>
	<section class="section-home py-5">
		<div class="container-xl container-fluid">
			<div class="row justify-content-center text-center">
				<div class="col-lg-12">
					<nav>
						<ol class="breadcrumb justify-content-center mb-3 text-light">
							<li class="breadcrumb-item"><a href="index.html">Home</a></li>
							<li class="breadcrumb-item active">Privacy Policy</li>
						</ol>
					</nav>
					<h1 class="fs-2 mb-0">Privacy Policy</h1>
				</div>
			</div>
		</div>
	</section>
	<section class="bg-custom-light py-5">
		<div class="container-xl container-fluid">
			<div class="row justify-content-center align-items-center text-justify">
				<div class="col-md-12">
					<h2 class="fs-4">INTRODUCTION</h2>
					<p>As part of our commitment to protecting your privacy, SpyderLab (hereinafter, Spyderlab, Spyderlab.org or the Company) maintains this policy.</p>
					<p>When you use our website or the Spyderlab SaaS (Software as a Service) (hereinafter, the Software), we may collect information about you (hereinafter, you or the customer), or that you may provide to us, and we will explain our practices for collecting, storing, using, maintaining, protecting and disclosing that information to you.</p>
					<p>We collect the following information:</p>
					<ul>
						<li>From the online registration, you may have completed when you subscribed for the Software or taken the premium plans.</li>
						<li>Your use of our site (including browsing activity and other usage information) and our software (including search queries and results generated by the Software).</li>
						<li>The computing environment through which you access and use our website.</li>
					</ul>
					<p>This policy explains our policies and practices regarding your information and how we will handle it. Please do not access our website or use the Software if you do not agree with our policies and practices. You agree to this privacy policy by using our website or the Software. Changes to Spyderlab's Privacy Policy may occur from time to time. Please check the policy periodically for updates if you continue to access our website or use the Software after we make changes.</p>
					<p>Our Software may generate search results that link to other websites. The privacy practices of those sites are not reflected in this policy.</p>

					<hr>

					<h2 class="fs-4">CORPORATE CUSTOMERS</h2>
					<p>Users who are employed by or affiliated with Spyderlab's customers (each, a customer) may only access and use Spyderlab's Software. After completing the online registration process, accepting Spyderlab's End User License Agreement (EULA), and receiving approval for access after Spyderlab has reviewed the information that the customer had entered during the online registration process, the customer is permitted to access Spyderlab's software.</p>

					<hr>

					<h2 class="fs-4">CHILDREN UNDER THE AGE OF 13</h2>
					<p>It is not intended for children under 13 years of age to access or use our website or Software, nor do we knowingly collect information about them. Our website is not for children under 13 years of age, so please do not access, use, or provide any information on it, including registering for the Software online, or providing us with any personal information, including your name, address, phone number, e-mail address, or screen name or user name. We will delete any personal information collected from children under 13 years of age if we discover it. Please <strong class="fw-bold">contact us</strong> if you think we may have information about a child under 13.</p>

					<hr>

					<h2 class="fs-4">HOW WE COLLECT INFORMATION ABOUT CUSTOMERS</h2>
					<p>The following information is collected from and about customers who visit our website or use the Software:</p>
					<ul>
						<li>Information that can be used to identify a customer or its employees, such as name, postal address, e-mail address, domain name, phone number, credit card number, employer ID number, or any other information input during the online registration process or collected by the Software during customer use that is deemed personally identifiable.</li>
						<li>Information about browsing activity, search queries, and results on our website and Software.</li>
						<li>Correspondence with a customer (including email addresses).</li>
						<li>A customer's computing environment when accessing our website.</li>
					</ul>
					<h3 class="fs-5">We collect this information when:</h3>
					<ul>
						<li>Provided by a customer as part of the online registration process or in another way.</li>
						<li>The customer accesses our website or uses the Software (including usage details, IP addresses, operating system, browser software, geolocation, and other information obtained through tracking technologies).</li>
						<li>The customer or user reports a problem or difficulty using our website or software.</li>
					</ul>
					<h3 class="fs-5">What We Do Not Collect</h3>
					<p>The automatic data collection technologies we use do not collect personally identifiable information about you, but they may be tied to other sources of information we collect about you or to the information you provide.</p>

					<hr>

					<h2 class="fs-4">OUR USE OF CUSTOMER INFORMATION</h2>
					<p>We make use of information that we collect about a customer or that a customer provides us, including any personal information:</p>
					<ul>
						<li>Our goal is to provide the customer with any information, products, or services they may need.</li>
						<li>If a customer provides it for any other purpose.</li>
						<li>Notifications about an account, including expiration and renewal notices, are provided to customers.</li>
						<li>Ensure that the EULA and any other terms governing a customer's use of our website or software are followed.</li>
						<li>According to applicable law, Spyderlab is required to fulfill its obligations under the EULA and any other contracts entered into between the customer and Spyderlab.</li>
						<li>Informing customers about changes to the Software or other products or services Spyderlab offers.</li>
						<li>For the purpose of improving the website or software.</li>
						<li>The information may be provided by customers in any other way Spyderlab sees fit.</li>
						<li>As long as the customer consents.</li>
					</ul>

					<hr>

					<h2 class="fs-4">CONFIDENTIALITY OF CUSTOMERS</h2>
					<p>It is unrestricted for us to disclose aggregate as well as non-identifying information about our customers. Our privacy policy describes how we may disclose personally identifiable information we collect or that you provide:</p>
					<ul>
						<li>To our subsidiaries and affiliates.</li>
						<li>Our business relies on contractors, service providers, and other third parties.</li>
						<li>When Spyderlab's assets are sold or transferred as part of a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer, whether as a going concern or as part of a bankruptcy, liquidation, or similar proceeding, and personal information about our customers is among the assets transferred.</li>
						<li>You provide it for a specific purpose.</li>
						<li>When you provide the information, we may use it for any other purpose disclosed to you.</li>
						<li>With your consent.</li>
					</ul>
					<p>Additionally, we may also disclose your personal information on the following conditions:</p>
					<ul>
						<li>Responding to the government or regulatory requests, as well as complying with any court order, law, or legal process.</li>
						<li>For billing and collection purposes, as well as for the enforcement of our EULA.</li>
						<li>Spyderlab, our customers, or others may be required to disclose the information if we believe it is necessary or appropriate to protect their rights, property, or safety.</li>
					</ul>

					<hr>

					<h2 class="fs-4">DATA SECURITY</h2>
					<p>In order to protect the privacy of your personal information, we have implemented reasonable measures designed to prevent accidental loss, unauthorized access, use, alteration, and disclosure. Our servers are protected by firewalls and we store all information you provide to us securely. Whenever any sensitive data is submitted or exchanged, it is encrypted using the TLS/SSL protocol(s).</p>
					<p>You are also responsible for the safety and security of your information. To access the Software, you must keep all usernames and passwords confidential.</p>
					<p>The internet does not provide complete security when it comes to transmitting the information. Despite our best efforts, we cannot guarantee the security of the information you transmit to our website or through the Software. It is at your own risk to transmit any personal information</p>

					<hr>

					<h2 class="fs-4">CONTACT INFORMATION</h2>
					<p>We welcome your questions about our privacy practices and this policy. Contact us here <a href="https://www.spyderlab.org/contact-us" target="_blank" title="Spyderlab" class="fw-bold custom-link">https://www.spyderlab.org/contact-us</a> or directly drop in a mail at <a href="mailto:spyd3rlab@gmail.com" class="fw-bold custom-link">spyd3rlab@gmail.com</a>. </p>
				</div>
			</div>
		</div>
	</section>
</main>
@endsection